basePath: /api/user
definitions:
  http.registerRequest:
    properties:
      login:
        type: string
      password:
        type: string
    required:
    - login
    - password
    type: object
  http.reqWithdraw:
    properties:
      order:
        type: string
      sum:
        type: integer
    type: object
  http.resBalance:
    properties:
      current:
        type: integer
      withdrawn:
        type: integer
    type: object
  http.resWithdraw:
    properties:
      order:
        type: string
      processed_at:
        type: string
      sum:
        type: integer
    type: object
  http.respOrder:
    properties:
      accrual:
        type: integer
      number:
        type: string
      status:
        type: string
      uploaded_at:
        type: string
    type: object
  http.response:
    properties:
      error:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: localhost:8080
info:
  contact:
    email: maybecoding@gmail.com
    name: Dmitry Petukhov
  description: Market for gophers
  title: Gopher Mart
  version: "1.0"
paths:
  /balance:
    get:
      consumes:
      - text/plain
      description: Returns balance on user. current is all bonuses minus withdrawn
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.resBalance'
        "401":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
      security:
      - JWT: []
      summary: Get Balance
      tags:
      - bonus
  /balance/withdraw:
    post:
      consumes:
      - text/plain
      description: Decreases bonuses by order amount
      parameters:
      - description: order and withdraw amount
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.reqWithdraw'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
        "401":
          description: No Content
        "402":
          description: Payment Required
          schema:
            $ref: '#/definitions/http.response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
      security:
      - JWT: []
      summary: Withdraw bonuses for order payment
      tags:
      - order
  /login:
    post:
      consumes:
      - application/json
      description: Login using login and password
      parameters:
      - description: login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.registerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
          headers:
            Set-Cookie:
              description: sets cookie
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
      summary: Login
      tags:
      - auth
  /orders:
    get:
      consumes:
      - text/plain
      description: Returns orders authorised by user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/http.respOrder'
            type: array
        "204":
          description: No Content
          schema:
            items:
              $ref: '#/definitions/http.respOrder'
            type: array
        "401":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
      security:
      - JWT: []
      summary: Get user orders
      tags:
      - order
    post:
      consumes:
      - text/plain
      description: Creates New Order
      parameters:
      - description: order ID
        in: body
        name: request
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.respOrder'
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/http.respOrder'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "401":
          description: No Content
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/http.response'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
      security:
      - JWT: []
      summary: Order Create
      tags:
      - order
  /register:
    post:
      consumes:
      - application/json
      description: Register using login and password
      parameters:
      - description: login and password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/http.registerRequest'
      produces:
      - application/json
      responses:
        "200":
          description: No Content
          headers:
            Set-Cookie:
              description: sets cookie
              type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.response'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/http.response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
      summary: Register
      tags:
      - auth
  /withdrawals:
    get:
      consumes:
      - text/plain
      description: Returns orders for withdrawals
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/http.resWithdraw'
            type: array
        "204":
          description: No Content
        "401":
          description: No Content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.response'
      security:
      - JWT: []
      summary: Get Withdrawals
      tags:
      - bonus
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
